'use client';
import Image from 'next/image'; import Link from 'next/link'; import { useEffect,useState } from 'react';
import { ArrowLeft,BookOpen,Check,CheckCircle2,ChevronLeft,ChevronRight,Lightbulb,Menu,Sparkles,X } from 'lucide-react';
import { lessons } from '@/lib/course-data';
const storageKey='kraft-course-completed';
export default function CourseApp(){const [active,setActive]=useState(0),[completed,setCompleted]=useState<string[]>([]),[drawer,setDrawer]=useState(false),[ready,setReady]=useState(false);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{setCompleted(JSON.parse(localStorage.getItem(storageKey)||'[]'))}catch{} setReady(true)},0);return()=>window.clearTimeout(timer)},[]);
 const lesson=lessons[active]; const progress=Math.round(completed.length/lessons.length*100);
 const toggle=()=>{const next=completed.includes(lesson.id)?completed.filter(x=>x!==lesson.id):[...completed,lesson.id];setCompleted(next);localStorage.setItem(storageKey,JSON.stringify(next))};
 const choose=(i:number)=>{setActive(i);setDrawer(false);window.scrollTo({top:0,behavior:'smooth'})};
 return <div className="min-h-screen bg-[#f7f7f4] text-[#18181b]"><header className="sticky top-0 z-40 border-b border-black/[.07] bg-[#f7f7f4]/90 backdrop-blur-xl"><div className="flex h-[72px] items-center gap-4 px-4 sm:px-6"><button onClick={()=>setDrawer(true)} className="rounded-xl border border-black/[.08] bg-white p-2.5 lg:hidden" aria-label="Open course menu"><Menu className="h-5 w-5"/></button><Link href="/" className="flex shrink-0 items-center"><Image src="/images/kraft-logo.png" alt="KRAFT" width={120} height={30}/></Link><div className="hidden h-5 w-px bg-black/10 sm:block"/><p className="hidden text-sm font-semibold sm:block">Web3 Career Course</p><div className="ml-auto flex items-center gap-3"><div className="hidden min-w-40 sm:block"><div className="flex justify-between text-[10px] font-bold"><span>COURSE PROGRESS</span><span>{ready?progress:0}%</span></div><Progress value={ready?progress:0}/></div><Link href="/" className="inline-flex items-center gap-2 rounded-full border border-black/[.08] bg-white px-4 py-2.5 text-xs font-bold"><ArrowLeft className="h-3.5 w-3.5"/><span className="hidden sm:inline">Back to home</span></Link></div></div><div className="px-4 pb-3 sm:hidden"><div className="mb-1 flex justify-between text-[9px] font-bold"><span>{lesson.number} / {lessons.length}</span><span>{progress}% complete</span></div><Progress value={progress}/></div></header>
 <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[280px_minmax(0,1fr)] xl:grid-cols-[280px_minmax(0,1fr)_260px]"><Sidebar active={active} completed={completed} choose={choose}/>
 <main className="min-w-0 px-4 py-8 sm:px-8 sm:py-12 lg:px-12 xl:px-16"><div className="mx-auto max-w-3xl"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em] text-purple-600"><span>{lesson.eyebrow}</span><span className="text-black/20">/</span><span className="text-muted">Lesson {lesson.number}</span></div><h1 className="mt-5 text-4xl font-semibold leading-[1.02] tracking-[-.055em] sm:text-6xl">{lesson.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#626168]">{lesson.intro}</p>
 <div className="course-visual mt-10"><div className="visual-orb visual-orb-a"/><div className="visual-orb visual-orb-b"/><div className="relative grid gap-3 sm:grid-cols-3"><div className="sm:col-span-2 rounded-2xl bg-white/90 p-5 shadow-xl shadow-purple-900/5"><span className="icon-tile"><BookOpen className="h-5 w-5"/></span><p className="mt-8 text-xs font-bold text-purple-600">THE KRAFT LOOP</p><h2 className="mt-2 text-2xl font-semibold tracking-[-.04em]">Learn → make → explain</h2><p className="mt-3 text-sm leading-6 text-muted">The goal of every lesson is a useful output and the language to defend your decisions.</p></div><div className="flex flex-col justify-between rounded-2xl bg-[#19191b] p-5 text-white"><Sparkles className="h-5 w-5 text-[#9e8dff]"/><div><strong className="text-3xl">{lesson.number}</strong><p className="mt-1 text-xs text-white/50">of {lessons.length} lessons</p></div></div></div></div>
 <section className="mt-14"><SectionLabel>Key takeaways</SectionLabel><div className="mt-5 grid gap-3 md:grid-cols-3">{lesson.takeaways.map((x,i)=><article key={x.title} className="rounded-2xl border border-black/[.07] bg-white p-5"><span className="text-xs font-bold text-purple-600">0{i+1}</span><h3 className="mt-8 font-semibold">{x.title}</h3><p className="mt-2 text-sm leading-6 text-muted">{x.text}</p></article>)}</div></section>
 <section className="mt-14 rounded-[26px] border border-black/[.07] bg-white p-5 sm:p-8"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-700"><CheckCircle2 className="h-5 w-5"/></span><div><SectionLabel>Practical task</SectionLabel><h2 className="mt-1 text-xl font-semibold">Complete before moving on</h2></div></div><div className="mt-7 space-y-3">{lesson.checklist.map((x,i)=><label key={x} className="flex cursor-pointer items-center gap-3 rounded-xl bg-[#f7f7f4] p-4 text-sm font-semibold"><input type="checkbox" className="h-4 w-4 accent-purple-600"/><span>{x}</span><span className="ml-auto text-xs text-muted">0{i+1}</span></label>)}</div></section>
 {lesson.glossary.map(x=><aside key={x.term} className="mt-6 flex gap-4 rounded-2xl border border-purple-100 bg-purple-50/70 p-5"><Lightbulb className="mt-0.5 h-5 w-5 shrink-0 text-purple-600"/><div><p className="text-xs font-bold uppercase tracking-wider text-purple-700">Glossary · {x.term}</p><p className="mt-2 text-sm leading-6 text-[#605b70]">{x.definition}</p></div></aside>)}
 <div className="mt-12 flex flex-col gap-3 border-t border-black/[.07] pt-7 sm:flex-row sm:items-center sm:justify-between"><button disabled={active===0} onClick={()=>choose(active-1)} className="inline-flex items-center gap-2 text-sm font-bold disabled:opacity-30"><ChevronLeft className="h-4 w-4"/>Previous lesson</button><button onClick={toggle} className={`inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-bold ${completed.includes(lesson.id)?'bg-emerald-100 text-emerald-800':'bg-[#18181b] text-white'}`}>{completed.includes(lesson.id)?<><Check className="h-4 w-4"/>Lesson completed</>:<>Mark lesson complete<CheckCircle2 className="h-4 w-4"/></>}</button><button disabled={active===lessons.length-1} onClick={()=>choose(active+1)} className="inline-flex items-center justify-end gap-2 text-sm font-bold disabled:opacity-30">Next lesson<ChevronRight className="h-4 w-4"/></button></div></div></main>
 <aside className="hidden border-l border-black/[.07] p-7 xl:block"><div className="sticky top-24"><SectionLabel>In this lesson</SectionLabel><nav className="mt-5 space-y-3 text-sm text-muted"><a href="#" className="block font-semibold text-foreground">Introduction</a><a href="#" className="block">Key takeaways</a><a href="#" className="block">Practical task</a><a href="#" className="block">Glossary</a></nav><div className="mt-8 rounded-2xl bg-[#eae6ff] p-5"><p className="text-xs font-bold text-purple-700">STUDY NOTE</p><p className="mt-3 text-sm leading-6 text-[#5d5675]">Don’t rush to finish. Publish one small artifact from each career-lane lesson.</p></div></div></aside></div>
 {drawer&&<div className="fixed inset-0 z-50 lg:hidden"><button className="absolute inset-0 bg-black/35" onClick={()=>setDrawer(false)} aria-label="Close menu"/><div className="absolute inset-y-0 left-0 w-[min(90vw,330px)] overflow-y-auto bg-[#f7f7f4] shadow-2xl"><div className="flex items-center justify-between border-b border-black/[.07] p-5"><strong>Course lessons</strong><button onClick={()=>setDrawer(false)}><X/></button></div><Sidebar active={active} completed={completed} choose={choose} mobile/></div></div>}</div>}
function Progress({value}:{value:number}){return <div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-black/[.08]"><div className="h-full rounded-full bg-gradient-to-r from-purple-600 to-blue-500 transition-all duration-700" style={{width:`${value}%`}}/></div>}
function Sidebar({active,completed,choose,mobile=false}:{active:number;completed:string[];choose:(i:number)=>void;mobile?:boolean}){return <aside className={`${mobile?'block':'hidden lg:block'} border-r border-black/[.07] bg-[#f3f2ee] p-4`}><div className={mobile?'':'sticky top-[88px]'}><p className="px-3 pb-3 text-[10px] font-bold uppercase tracking-[.16em] text-muted">Course curriculum</p><nav className="space-y-1">{lessons.map((l,i)=><button key={l.id} onClick={()=>choose(i)} className={`group flex w-full items-start gap-3 rounded-xl px-3 py-3 text-left transition ${active===i?'bg-white shadow-sm':'hover:bg-white/60'}`}><span className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-[9px] font-bold ${completed.includes(l.id)?'bg-emerald-500 text-white':active===i?'bg-purple-600 text-white':'border border-black/10 text-muted'}`}>{completed.includes(l.id)?<Check className="h-3 w-3"/>:l.number}</span><span><strong className={`block text-xs leading-5 ${active===i?'text-foreground':'text-[#66646a]'}`}>{l.title}</strong><small className="mt-0.5 block text-[9px] uppercase tracking-wide text-muted">{l.eyebrow}</small></span></button>)}</nav></div></aside>}
function SectionLabel({children}:{children:React.ReactNode}){return <p className="text-[10px] font-bold uppercase tracking-[.17em] text-purple-600">{children}</p>}
