'use client';
import { useState } from 'react';
import { Eye, MessageSquareText, RotateCcw } from 'lucide-react';
const cards=[
 ['What is the EVM, and why does gas exist?','Explain the execution environment first, then connect gas to scarce computation, spam prevention, and validator incentives. Strong answers mention tradeoffs.'],
 ['Walk me through a project you shipped.','Use context → decision → implementation → result. Be precise about your contribution and name one thing you would improve.'],
 ['How would you prevent a reentrancy attack?','Describe checks-effects-interactions, reentrancy guards, careful external calls, and testing. Show that security is a process, not one modifier.'],
 ['Why do you want to work in Web3?','Skip generic decentralization slogans. Connect a real user problem, relevant proof of work, and why this team is the right place to solve it.'],
];
export default function InterviewPage(){const [flipped,setFlipped]=useState<number[]>([]);return <main className="min-h-screen bg-[#f6f8fc] px-4 pb-24 pt-36"><div className="mx-auto max-w-5xl"><div className="text-center"><span className="section-kicker">Interview practice</span><h1 className="mt-4 text-4xl font-extrabold tracking-[-.05em] md:text-6xl">Practice the answer behind the answer.</h1><p className="mx-auto mt-5 max-w-2xl leading-7 text-slate-600">Flip each card to see what a strong response should demonstrate—not a script to memorize.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{cards.map(([q,a],i)=>{const open=flipped.includes(i);return <button key={q} onClick={()=>setFlipped(open?flipped.filter(x=>x!==i):[...flipped,i])} className={`min-h-72 rounded-3xl border p-7 text-left shadow-sm transition duration-300 hover:-translate-y-1 hover:shadow-xl ${open?'border-blue-600 bg-blue-600 text-white':'border-slate-200 bg-white'}`}><div className="flex items-center justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${open?'bg-white/15':'bg-blue-50 text-blue-600'}`}>{open?<RotateCcw/>:<MessageSquareText/>}</span><span className={`text-xs font-black uppercase tracking-widest ${open?'text-blue-100':'text-slate-400'}`}>{open?'What to demonstrate':`Question 0${i+1}`}</span></div><h2 className="mt-8 text-2xl font-bold leading-tight">{open?a:q}</h2><div className={`mt-8 flex items-center gap-2 text-sm font-bold ${open?'text-blue-100':'text-blue-600'}`}><Eye className="h-4 w-4"/>{open?'Show question':'Reveal guidance'}</div></button>})}</div></div></main>}
