'use client';
import { useEffect, useState } from 'react';
import { Check, Route } from 'lucide-react';
const weeks=[
 {title:'Week 1 — Understand the terrain',items:['Learn how wallets and transactions work','Compare L1s, L2s, and appchains','Use a block explorer confidently']},
 {title:'Week 2 — Build the fundamentals',items:['Complete Solidity syntax basics','Write and test a simple contract','Learn common smart contract risks']},
 {title:'Week 3 — Ship in public',items:['Deploy a contract to testnet','Create a clear project README','Share a short build log']},
 {title:'Week 4 — Become interview ready',items:['Review five technical questions','Polish your GitHub profile','Apply to three carefully matched roles']},
];
export default function RoadmapPage(){const [done,setDone]=useState<string[]>([]);useEffect(()=>{const timer=window.setTimeout(()=>setDone(JSON.parse(localStorage.getItem('kraft-roadmap')||'[]')),0);return()=>window.clearTimeout(timer)},[]);const toggle=(x:string)=>{const next=done.includes(x)?done.filter(i=>i!==x):[...done,x];setDone(next);localStorage.setItem('kraft-roadmap',JSON.stringify(next))};const total=weeks.flatMap(w=>w.items).length;return <main className="min-h-screen bg-white px-4 pb-24 pt-36"><div className="mx-auto max-w-5xl"><div className="grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><div><span className="section-kicker">30-day roadmap</span><h1 className="mt-4 text-4xl font-extrabold tracking-[-.05em] md:text-6xl">Go from curious to credible.</h1><p className="mt-5 leading-7 text-slate-600">A focused starter plan for aspiring blockchain developers. Your progress is saved on this device.</p><div className="mt-8 rounded-2xl bg-slate-950 p-6 text-white"><Route className="text-blue-400"/><div className="mt-5 flex items-end justify-between"><strong className="text-4xl">{done.length}<span className="text-lg text-slate-500">/{total}</span></strong><span className="text-sm font-bold text-slate-400">tasks complete</span></div><div className="mt-4 h-2 rounded-full bg-slate-800"><div className="h-full rounded-full bg-blue-500 transition-all" style={{width:`${done.length/total*100}%`}}/></div></div></div><div className="space-y-5">{weeks.map((week,i)=><section key={week.title} className="rounded-3xl border border-slate-200 bg-[#f8fafc] p-6"><div className="flex items-center gap-4"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-600 font-black text-white">{i+1}</span><h2 className="text-lg font-bold">{week.title}</h2></div><div className="mt-5 space-y-3">{week.items.map(item=><button onClick={()=>toggle(item)} key={item} className={`flex w-full items-center gap-3 rounded-xl border p-4 text-left text-sm font-semibold transition ${done.includes(item)?'border-emerald-200 bg-emerald-50 text-slate-500 line-through':'border-slate-200 bg-white hover:border-blue-300'}`}><span className={`flex h-6 w-6 flex-none items-center justify-center rounded-full ${done.includes(item)?'bg-emerald-500 text-white':'border-2 border-slate-200'}`}>{done.includes(item)&&<Check className="h-4 w-4"/>}</span>{item}</button>)}</div></section>)}</div></div></div></main>}
