export type Lesson = {
  id: string; number: string; title: string; eyebrow: string; intro: string;
  takeaways: { title: string; text: string }[]; checklist: string[]; glossary: { term: string; definition: string }[];
};

export const lessons: Lesson[] = [
  { id:'introduction', number:'01', title:'Start with the work, not the title', eyebrow:'Introduction', intro:'Web3 job titles are inconsistent. This course helps you identify the work you enjoy, practice it in public, and apply with evidence instead of enthusiasm alone.', takeaways:[{title:'Choose a lane',text:'Match your strengths to a real category of work.'},{title:'Learn in public',text:'Turn every module into a small, inspectable output.'},{title:'Apply later',text:'Build context before you enter a hiring process.'}], checklist:['Write down three tasks you enjoy doing','Pick one role path to explore first','Create a folder for your proof-of-work'], glossary:[{term:'Proof-of-work',definition:'A practical artifact that demonstrates how you think and execute.'}]},
  { id:'web3-work', number:'02', title:'What Web3 work actually means', eyebrow:'Foundations', intro:'The industry runs on open networks, global communities, tokens, and fast feedback loops. The fundamentals matter because every role works around the same systems.', takeaways:[{title:'Open by default',text:'Products, transactions, and communities are unusually visible.'},{title:'Context compounds',text:'Protocol literacy makes every non-technical role stronger.'},{title:'Risk is real',text:'Clear communication and operational judgment matter.'}], checklist:['Use a block explorer to inspect a transaction','Compare a mainnet and testnet','Explain a smart contract in plain English'], glossary:[{term:'dApp',definition:'An application whose core logic interacts with a blockchain.'},{term:'Gas fee',definition:'The network fee paid to process a blockchain transaction.'}]},
  { id:'career-lanes', number:'03', title:'Map the career lanes', eyebrow:'Explore roles', intro:'Roles cluster around a few repeatable kinds of work: community, content, growth, product, research, design, and engineering.', takeaways:[{title:'Community',text:'Support users and turn feedback into trust.'},{title:'Research',text:'Translate on-chain and market signals into insight.'},{title:'Product',text:'Coordinate user needs, constraints, and delivery.'}], checklist:['Shortlist two non-technical paths','Shortlist one stretch path','Compare their daily tasks'], glossary:[{term:'Contributor',definition:'A person who performs scoped work for a protocol, DAO, or ecosystem.'}]},
  { id:'community-growth', number:'04', title:'Community & growth', eyebrow:'Career lane', intro:'Healthy communities are built through systems, useful programs, and honest feedback—not vanity metrics or constant posting.', takeaways:[{title:'Listen first',text:'Support patterns reveal product and communication gaps.'},{title:'Design loops',text:'Give members useful reasons to return and contribute.'},{title:'Measure health',text:'Track retention, resolution, and meaningful participation.'}], checklist:['Draft a delayed-airdrop response','Create a weekly community report','Outline one contributor campaign'], glossary:[{term:'KPI',definition:'A key performance indicator tied to a meaningful outcome.'}]},
  { id:'content-research', number:'05', title:'Content & research', eyebrow:'Career lane', intro:'Great Web3 content makes complex systems understandable without removing the important nuance.', takeaways:[{title:'Find the claim',text:'Every piece needs one clear, defensible point.'},{title:'Show receipts',text:'Link primary sources and explain assumptions.'},{title:'Match the reader',text:'Structure depth around the audience’s context.'}], checklist:['Write a 200-word protocol breakdown','Build a source checklist','Rewrite one technical concept for a beginner'], glossary:[{term:'TVL',definition:'Total value locked in a protocol’s smart contracts.'}]},
  { id:'product-ops', number:'06', title:'Product & operations', eyebrow:'Career lane', intro:'Product and ops roles make ambiguous work legible: what matters, who owns it, and how the team will know it worked.', takeaways:[{title:'Frame the problem',text:'Separate user pain from requested features.'},{title:'Reduce ambiguity',text:'Document decisions, owners, and dependencies.'},{title:'Ship a loop',text:'Release, learn, and update the plan.'}], checklist:['Write a one-page product brief','Prioritize five feature requests','Create a launch readiness checklist'], glossary:[{term:'Async work',definition:'Collaboration designed not to require everyone online simultaneously.'}]},
  { id:'defi-analysis', number:'07', title:'DeFi & on-chain analysis', eyebrow:'Research lane', intro:'On-chain analysts combine blockchain data with product and market context. A dashboard is only useful when the interpretation is careful.', takeaways:[{title:'Trace behavior',text:'Transactions reveal actions, not always intent.'},{title:'Define metrics',text:'Know exactly what each number includes.'},{title:'State limits',text:'Good analysis makes uncertainty visible.'}], checklist:['Inspect a protocol dashboard','Define TVL and volume','Write three caveats for your analysis'], glossary:[{term:'AMM',definition:'An automated market maker that prices assets using a liquidity pool.'}]},
  { id:'technical-roles', number:'08', title:'Technical roles', eyebrow:'Builder lane', intro:'Engineering, DevRel, and technical writing require different depths of code, but all reward precise thinking and visible projects.', takeaways:[{title:'Build small',text:'One finished integration beats five tutorials.'},{title:'Explain choices',text:'Document tradeoffs and debugging decisions.'},{title:'Protect users',text:'Security thinking is part of the job.'}], checklist:['Deploy a testnet project','Document the architecture','Write a useful README'], glossary:[{term:'Account abstraction',definition:'A design approach that makes blockchain accounts programmable and easier to use.'}]},
  { id:'proof-of-work', number:'09', title:'Build proof-of-work', eyebrow:'Portfolio builder', intro:'Your portfolio should reduce hiring risk. Each artifact needs a clear brief, thoughtful decisions, and a result someone can inspect quickly.', takeaways:[{title:'Make it relevant',text:'Build the kind of output the role produces.'},{title:'Add a brief',text:'Explain audience, constraints, and success criteria.'},{title:'Show thinking',text:'A polished artifact without rationale is incomplete.'}], checklist:['Publish a sample announcement','Complete a protocol breakdown','Create a campaign or product plan','Build a simple portfolio page'], glossary:[{term:'Deliverables',definition:'The specific outputs agreed for a project or engagement.'}]},
  { id:'interview-prep', number:'10', title:'Practice the interview', eyebrow:'Interview prep', intro:'Strong answers combine a clear structure with role judgment. Practice aloud until your reasoning is concise, calm, and specific.', takeaways:[{title:'Use evidence',text:'Anchor claims in a project or real scenario.'},{title:'Name tradeoffs',text:'Show that you can make decisions under constraints.'},{title:'Close the loop',text:'Explain how you would measure and learn.'}], checklist:['Record four practice answers','Prepare three project stories','Write five questions for the team'], glossary:[{term:'Retainer',definition:'A recurring payment for an agreed scope or availability.'}]},
  { id:'apply-context', number:'11', title:'Apply with context', eyebrow:'Next step', intro:'A focused application demonstrates that you understand the product, the role, and the most useful contribution you could make first.', takeaways:[{title:'Research first',text:'Understand the product, users, and recent priorities.'},{title:'Lead with value',text:'Share one relevant insight or artifact.'},{title:'Track the process',text:'Improve your applications from actual feedback.'}], checklist:['Build a 20-company target list','Write a contextual outreach note','Track applications and follow-ups'], glossary:[{term:'Token compensation',definition:'Compensation paid partly or fully in a project’s token, with distinct liquidity and risk.'}]},
];

export const rolePaths = [
 ['Community Manager','Beginner','Community · No-code','Build trust, programs, and useful feedback loops.'],['Content Creator','Beginner','Writing · Creative','Turn complex ideas into useful, memorable content.'],['DeFi Analyst','Intermediate','Research · Data','Interpret protocol activity, risk, and market context.'],['Web3 Product Manager','Intermediate','Product · Strategy','Turn user problems into focused product decisions.'],['Ecosystem / BD','Intermediate','Growth · No-code','Create partnerships that produce measurable adoption.'],['Smart Contract Developer','Advanced','Technical','Build and secure on-chain product logic.'],['DevRel','Advanced','Technical · Community','Help developers succeed with tools and education.'],['Technical Writer','Intermediate','Writing · Technical','Create precise docs that unblock builders.'],['UI/UX Designer','Intermediate','Design · Product','Make complex blockchain actions feel understandable.'],
];

export const modules = ['Web3 Foundations','Career Lanes','Community & Growth','Content & Research','Product & Ops','Technical Roles','Portfolio Builder','Interview Prep','Job Board Strategy'];
export const interviewQuestions = ['How would you handle angry users after a delayed airdrop?','How do you evaluate a protocol before writing about it?','How do you measure community health?','What would you build first as a Web3 PM?'];
