import Link from 'next/link';
import { ArrowRight, CheckCircle2, Github, PenTool, Rocket, ShieldCheck } from 'lucide-react';
const sections=[
 {icon:Github,title:'Project evidence',items:['Public GitHub repo with clear commit history','Readable README with setup instructions','Live demo, testnet deployment, or product screenshots']},
 {icon:PenTool,title:'Thinking evidence',items:['One technical write-up explaining tradeoffs','A short thread or article summarizing what you learned','Documentation that another beginner can follow']},
 {icon:ShieldCheck,title:'Trust evidence',items:['Tests, audit notes, or known limitations','No private keys or secrets in repositories','Explicitly listed dependencies and risks']},
 {icon:Rocket,title:'Distribution evidence',items:['Shared in at least one relevant community','Feedback incorporated in a changelog','A concise portfolio landing page linking everything']},
];
export default function PortfolioPage(){return <main className="min-h-screen bg-white px-4 pb-24 pt-36"><div className="mx-auto max-w-6xl"><div className="mx-auto max-w-3xl text-center"><span className="section-kicker">Portfolio builder</span><h1 className="mt-4 text-4xl font-extrabold tracking-[-.05em] md:text-6xl">Make recruiters trust your signal fast.</h1><p className="mt-5 leading-7 text-slate-600">A Web3 portfolio should prove that you can ship, explain your decisions, and operate safely in public.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{sections.map(({icon:Icon,title,items})=><section className="rounded-3xl border border-slate-200 bg-[#f8fafc] p-7" key={title}><div className="flex items-center gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-600 text-white"><Icon/></span><h2 className="text-2xl font-bold tracking-tight">{title}</h2></div><ul className="mt-6 space-y-4">{items.map(item=><li className="flex gap-3 text-sm font-semibold leading-6 text-slate-700" key={item}><CheckCircle2 className="mt-0.5 h-5 w-5 flex-none text-emerald-500"/>{item}</li>)}</ul></section>)}</div><div className="mt-12 rounded-3xl bg-slate-950 p-8 text-white md:p-10"><p className="text-sm font-bold uppercase tracking-[.16em] text-blue-300">Recommended next step</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Pick one role, then build one small but complete artifact.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-400">A focused portfolio beats a scattered one. Tie every project back to the role you want and the skill it proves.</p><Link href="/roles" className="button-light mt-8">Choose a role <ArrowRight className="h-4 w-4"/></Link></div></div></main>}
